# Problem 1

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
my_matrix = np.random.randint(0,10,size=5)
print(my_matrix)
# 3 - matris'in boyutunu öğrenin
print(my_matrix.shape)
# 4 - matris'i yeniden boyutlandırın
new_matrix= my_matrix.reshape(5,1)
print(new_matrix)
# 5 - matris'in boyut sayısını öğrenin
print(new_matrix.ndim)

[7 1 6 6 6]
(5,)
[[7]
 [1]
 [6]
 [6]
 [6]]
2


# Problem 2

In [3]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
mtrx= np.arange(1,10,2)
print(mtrx)
# 2 - Oluşturduğunuz matrisi parçalayın
a,b,c=np.split(mtrx,[2,4])
print(a,b,c)
# 3 - Parçalanmış matrisleri birleştirin
birlesim= np.concatenate([a,b,c])
print(birlesim)

[1 3 5 7 9]
[1 3] [5 7] [9]
[1 3 5 7 9]


# Problem 3

In [5]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import random
my_list=list(np.arange(5,100,2))
my_list
random10 = random.sample(my_list,10)
print(random10)
mtrs10 = np.array(random10)
print(mtrs10)
# 2 - matris'in özelliklerini inceleyin
print(mtrs10.shape)
print(mtrs10.ndim)


[53, 5, 11, 55, 51, 81, 87, 37, 77, 7]
[53  5 11 55 51 81 87 37 77  7]
(10,)
1
