# Problem 1 

In [21]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
array_p1 = np.array([5,4,3,2,1])
print(array_p1)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array_p1.sort()
print(array_p1)


[5 4 3 2 1]
[1 2 3 4 5]


# Problem 2

In [98]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array_1 = np.array([10,15,30,45,60])
print(array_1)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array_2 = np.arange(5,15,1)
print(array_2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array_3 = np.arange(50,100,5)
print(array_3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array_4= np.zeros(10)
print(array_4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array_5= np.ones(10)
print(array_5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array_6=np.linspace(0,100,5)
print(array_6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
import random
array_7=np.random.randint(10,30,5)
print(array_7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array_8=np.random.uniform(-1,1,10)
print(array_8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
array_9=np.random.randint(10,50,15)
matris_9=array_9.reshape(3,5)
print(matris_9)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
matris_9.shape

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(matris_9.min())
print(matris_9.max())
print(matris_9.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(matris_9.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array_10= np.arange(10,20,1)
array_f3 = array_10[0:3]
print(array_f3)
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array_f3[len(array_f3)::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris_9[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris_9[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris_9[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.power(matris_9,2))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
array_9=np.random.randint(-50,50,15)
matris_9=array_9.reshape(3,5)
print(matris_9)
print(matris_9[(matris_9>0) & (matris_9%2==0)])



[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[20 15 14 21 12]
[ 0.31076112 -0.68529168  0.70496005 -0.7439041  -0.32778646  0.34898184
  0.8098563  -0.70436687 -0.40860073  0.92690435]
[[31 22 23 30 30]
 [22 15 32 32 48]
 [48 24 49 28 17]]
15
49
30.066666666666666
12
[10 11 12]
[12 11 10]
[31 22 23 30 30]
32
[31 22 48]
[[ 961  484  529  900  900]
 [ 484  225 1024 1024 2304]
 [2304  576 2401  784  289]]
[[ -8  -5 -49   3 -29]
 [ 28  -5   3  18 -32]
 [ 40  40  37 -33 -24]]
[28 18 40 40]
